keycloak:
  environment:
    KEYCLOAK_USER: ${KEYCLOAK_USER}
    KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    MYSQL_PORT_3306_TCP_ADDR: ${MYSQL_HOST}
    MYSQL_PORT_3306_TCP_PORT: "3306"
    MYSQL_HOST: ${MYSQL_HOST}
    MYSQL_USERNAME: ${MYSQL_KEYCLOAK_USER}
    MYSQL_PASSWORD: ${MYSQL_KEYCLOAK_Password}
    MYSQL_DATABASE: ${MYSQL_KEYCLOAK_DATABASE}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: keycloak-datavolume
  tty: true
  image: jboss/keycloak-mysql:3.2.1.Final
  stdin_open: true
  volumes_from:
    - keycloak-datavolume
keycloak-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  command: chown -R 1000 /opt/jboss/keycloak/standalone/data
  volumes:
    - /opt/jboss/keycloak/standalone/data
  image: busybox
