version: '2'
services:
  questions:
    - variable: VAMP_CONTAINER_DRIVER_RANCHER_URL
      description: "Vamp Rancher API Url"
      label: "Vamp Env API"
      type: "string"
      required: true
  questions:
    - variable: VAMP_CONTAINER_DRIVER_RANCHER_USER
      description: "Vamp API Access User"
      label: "Vamp API Access User"
      type: "string"
      required: true
  questions:
    - variable: VAMP_CONTAINER_DRIVER_RANCHER_PASSWORD
      description: "Vamp API Access Secret Password"
      label: "Vamp API Access Secret Password"
      type: "string"
      required: true
  vamp-gateway-agent:
    start_on_create: true
  consul:
    scale: 1
    start_on_create: true
  elastic:
    scale: 1
    start_on_create: true
  vamp:
    scale: 1
    start_on_create: true
  vamp-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: vamp
        source_port: 9090
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
